services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/app:cached
    command: sleep infinity
    environment:
      - OPENAI_API_URL=http://model-runner.docker.internal/engines/v1

    # models:
    #   - llm

models:
  llm:
    model: ai/gemma3