services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../:/app:cached

    # Mantém o container ativo
    command: sleep infinity

    # Referência ao modelo
    models:
      - llm

models:
  llm:
    model: ai/gemma3
